sudo: required
dist: xenial
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

install:
  - pip install codecov

script:
  - coverage run setup.py test

after_success:
  - codecov